<Project Sdk="Microsoft.NET.Sdk"> <PropertyGroup> <OutputType>Exe</OutputType> <TargetFramework>net8.0</TargetFramework> <ImplicitUsings>enable</ImplicitUsings> <Nullable>enable</Nullable> </PropertyGroup> <ItemGroup> <Compile Remove="Fraction.cs" /> <Compile Remove="FractionCalculator .cs" /> </ItemGroup> <ItemGroup> <PackageReference Include="ScottPlot" Version="5.1.57" /> <PackageReference Include="Telegram.Bot" Version="22.8.1" /> </ItemGroup> </Project>